#!/usr/bin/env python2
import os,sys
from subprocess import call
from PIL import Image

def make_thumb(src, out, size):
    if size == "":
        size = 128
    call(["wkhtmltoimage", "-n", "--no-images", src, out])
    img = Image.open(out)
    area = (0, 0, size, size*1.5)
    img.crop(area).save(out, "PNG")
    
    pass


def main(argv):
    i = 0;
    
    # initial variables
    source = ""
    size = ""
    output = ""

    for arg in argv:
        if i == 1:
            source = argv[i]
        elif i == 2:
            output = argv[i]
        elif i == 3:
            size = int(argv[i])
        
        i += 1
    
    make_thumb(source, output, size)
    pass

if __name__ == '__main__':
    sys.exit(main(sys.argv))
